---
title: "LONG BEACH ANIMAL SHELTER PROJECT"
author: "Thu Nguyen"
date: "2025-02-25"
output: html_document
---
### MEET THE ANIMALS

The `animals` dataset comprises of the intake and outcome record from Long Beach Animal Shelter.

1. How has the number of per adoptions changed over years ?

2. Which type of pets are adopted most often ?
```{r}
# Data Preparation
library(lubridate)
library(dplyr)
library(ggplot2)
library(tidytuesdayR)

tuesdata <- tidytuesdayR::tt_load(2025, week = 9)
adoptions <- tuesdata$longbeach
str(adoptions)

adoptions$Date <- as.Date(adoptions$outcome_date, format = "%Y-%m-%d")
adoptions$Year <- year(adoptions$Date)

# Question 1:

adoptions_by_year <- adoptions %>%
  group_by(Year) %>%
  summarise(TotalAdoptions = n()) %>%
  arrange(Year)
print(adoptions_by_year) # summary tables

ggplot(adoptions_by_year, aes(x = Year, y = TotalAdoptions)) + 
  geom_line(color = "darkblue", size = 1) +
  geom_point(color = "red", size = 2) +
  labs(title = "Number of Animals Adoptions Over The Years",
       x = "Year",
       y = "Total Adoptions") +
  theme_minimal()

# Based off the analysis and the data, there was an initially high level of adoptions in the earlier years, suggesting a period when many families and individuals were ready and eager to bring home new pets. However, as time moved on, adoption numbers dipped, hitting their lowest point around 2020, which was really odd. As there was a lot of news talking about how during the COVID-19, many families and individuals welcomed new pets from shelters.During periods of stress or instability, adoption rates often fall, as the demands of daily life overshadow the dream of bringing a furry companion home. Starting from 2022, the numbers began a steady recovery, climbing each subsequent year. By 2024, adoptions are higher than they've been in quite some time.
```
```{r}
# Question 2: 

adoptions_by_pet <- adoptions %>%
  group_by(animal_type) %>%
  summarise(TotalAdoptions = n()) %>%
  arrange(desc(TotalAdoptions))
print(adoptions_by_pet)

ggplot(adoptions_by_pet, aes(x = reorder(animal_type, TotalAdoptions), y = TotalAdoptions)) +
  geom_bar(stat = "identity", fill = "steelblue") +
  coord_flip() +
  labs(title = "Most Adopted Animal Types",
       x = "Animal Type",
       y = "Number of Adoptions") +
  theme_minimal()

# From the chart, it’s clear that cats have taken the top spot as the most frequently adopted animal type, followed closely by dogs. After these two perennial favorites, adoption numbers drop considerably for other types of pets such as birds, rabbits, reptiles, and small mammals like guinea pigs.
```
